### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [bertdida/TwitterQuoteScraper#2]
Hello @bertdida  I am a graphic artist and I would like to contribute to your project by designing a logo for it. I already have an idea in mind. If you are interested I will begin my design asap. - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by bertdida** [comment]
Hi @Tobaloidee , I'm glad you're interested on contributing to this one! Would love to see your design 😀

**Comment by Tobaloidee** [comment]
Thank you for the quick response @bertdida . Will show you my design here as soon as i finished it! 👍

**Comment by bertdida** [comment]
Awesome! :)

**Comment by Tobaloidee** [comment]
Here's what I came up with @bertdida  I hope you like it and just tell me if you have any suggestions.

-I created a Minimal but Meaningful design which I think will fit your project well as I also used a bird symbol particularly "Woodpecker" which embodies the function of "scraping" combined with the Quotation marks that can be seen incorporated into the bird's body.
![TWITTERQUOTESCRAPER-01](https://user-images.githubusercontent.com/36028424/56118565-d1265d00-5f9c-11e9-92df-487c63e74404.png)

**Comment by bertdida** [comment]
Nice! I like the idea behind.

Maybe it would look much cleaner if we make its back rounder and shift the comb (hair) a little? What do you think?

![Screenshot_9](https://user-images.githubusercontent.com/38489033/56120749-60ce0a80-5fa1-11e9-8529-8c8fcd807fcf.png)

**Comment by Tobaloidee** [comment]
Sure! Will edit it again for that suggestions..how bout the color?

**Comment by bertdida** [comment]
I'm thinking about the plain black and the Twitters accents sky blue color. I'm not sure.

**Comment by Tobaloidee** [comment]
twitter blue is perfect

![TWITTERQUOTESCRAPER-02](https://user-images.githubusercontent.com/36028424/56122148-4b0e1480-5fa4-11e9-8441-fb445460d04a.png)

**Comment by bertdida** [comment]
Couldn't agree more! This one's perfect!

I'll update the README tomorrow and will give credits to you. Thank you @Tobaloidee ! :)

**Comment by bertdida** [comment]
BTW where I can download the file?

**Comment by Tobaloidee** [comment]
i can make the PR and upload the files..will finalize it now..i will share my drive also for the black and white versions

**Comment by bertdida** [comment]
Got it. Will check tomorrow :)

**Comment by Tobaloidee** [comment]
Here's the PR #3 with the logo upload and readme update and also, here is the link to my [DRIVE](https://drive.google.com/drive/u/1/folders/1D60jvnWyYX7tiHyflcpJeFVQJ8-aUQYp) where you can download all the versions and formats needed. Thanks so much for accepting my design @bertdida 

Best regards!

**Comment by bertdida** [comment]
PR merged.

You're welcome @Tobaloidee! Best of luck on both of our careers. Will close this issue now.
